spring:
  liquibase:
    change-log: classpath:db/changelog/migration.xml
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: gff5j!d@jf0%^o
  expiration: 330000
